name: Run version test action
description: |
  For testing only.
inputs:
  git_sha:
    description: sha of currently checked out commit
    required: true
runs:
  using: composite
  steps:
    - name: Print version
      shell: bash
      run: |
        echo "Hello world! This is action version 1."
        echo "inputs.git_sha: ${{ inputs.git_sha }}"
        echo "github.sha: ${{ github.sha }}"
        echo "github.action_ref: ${{ github.action_ref }}"