name: "Protected tag test"
on:
  workflow_dispatch:
    inputs:
      git_sha:
        description: The SHA hash of the commit being deployed
        type: string
        required: true

jobs:
  push-protected-tag:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ inputs.git_sha }}
      - name: Update tag
        run: |
          git tag -f well-protected-tag ${{ inputs.git_sha }}
          git push -f origin well-protected-tag
